# This file contains values from Cookiecutter

default_context:
  project_name: "tracking-ui"
  project_description: "Awesome `tracking-ui` is a Python cli/package created with https://github.com/will-wright-eng/cookiecutter-pypackage-slim"
  organization: "tracking-ui"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "will-wright-eng"
  email: "hello@tracking-ui.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
