version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    - '${HOME}/.aws/:/root/.aws/'

    environment:
      # Enables autoreload.
      TRACKING_UI_RELOAD: "True"
